name: release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          token: ${{ secrets.FENSAK_OPS_CI_TOKEN }}

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: "lts/*"

      - name: import gpg signing key
        uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
        with:
          gpg_private_key: ${{ secrets.FENSAK_OPS_CI_GPG }}
          passphrase: ${{ secrets.FENSAK_OPS_CI_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: "fensak-ops"
          git_committer_email: "118200068+fensak-ops@users.noreply.github.com"

      - name: Release
        run: |
          npm install @semantic-release/exec
          npx -y semantic-release@v19
        env:
          GIT_AUTHOR_NAME: "fensak-ops"
          GIT_AUTHOR_EMAIL: "118200068+fensak-ops@users.noreply.github.com"

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: release-notes
          path: /tmp/release-notes.md

  goreleaser:
    name: upload binaries
    runs-on: ubuntu-latest
    needs: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          fetch-depth: 0

      - uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: 1.19
          cache: true

      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: release-notes
          path: /tmp

      - uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v4.2.0
        with:
          distribution: goreleaser
          version: latest
          # NOTE: we use parallelism 1 because the cosign process is not concurrency safe.
          args: release --parallelism 1 --release-notes /tmp/release-notes.md --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_EXPERIMENTAL: true
